# Project information
site_name: FreeType-2.9.1 API Reference
site_author: FreeType Contributors
docs_dir: markdown
site_dir: site

# Configuration
theme:
  language: en
  logo: images/favico.ico
  name: material

# Pages
pages:
- TOC: ft2-toc.md
- Index: ft2-index.md
- General Remarks:
  - FreeType's header inclusion scheme: ft2-header_inclusion.md
  - User allocation: ft2-user_allocation.md
- Core API:
  - FreeType Version: ft2-version.md
  - Basic Data Types: ft2-basic_types.md
  - Base Interface: ft2-base_interface.md
  - Unicode Variation Sequences: ft2-glyph_variants.md
  - Glyph Management: ft2-glyph_management.md
  - Mac Specific Interface: ft2-mac_specific.md
  - Size Management: ft2-sizes_management.md
  - Header File Macros: ft2-header_file_macros.md
- Format-Specific API:
  - Multiple Masters: ft2-multiple_masters.md
  - TrueType Tables: ft2-truetype_tables.md
  - Type 1 Tables: ft2-type1_tables.md
  - SFNT Names: ft2-sfnt_names.md
  - BDF and PCF Files: ft2-bdf_fonts.md
  - CID Fonts: ft2-cid_fonts.md
  - PFR Fonts: ft2-pfr_fonts.md
  - Window FNT Files: ft2-winfnt_fonts.md
  - Font Formats: ft2-font_formats.md
  - Gasp Table: ft2-gasp_table.md
- Controlling FreeType Modules:
  - The auto-hinter: ft2-auto_hinter.md
  - The CFF driver: ft2-cff_driver.md
  - The Type 1 and CID drivers: ft2-t1_cid_driver.md
  - The TrueType driver: ft2-tt_driver.md
  - The PCF driver: ft2-pcf_driver.md
  - Driver properties: ft2-properties.md
  - Parameter Tags: ft2-parameter_tags.md
- Cache Sub-System:
  - Cache Sub-System: ft2-cache_subsystem.md
- Support API:
  - Computations: ft2-computations.md
  - List Processing: ft2-list_processing.md
  - Outline Processing: ft2-outline_processing.md
  - Quick retrieval of advance values: ft2-quick_advance.md
  - Bitmap Handling: ft2-bitmap_handling.md
  - Scanline Converter: ft2-raster.md
  - Glyph Stroker: ft2-glyph_stroker.md
  - System Interface: ft2-system_interface.md
  - Module Management: ft2-module_management.md
  - GZIP Streams: ft2-gzip.md
  - LZW Streams: ft2-lzw.md
  - BZIP2 Streams: ft2-bzip2.md
  - Subpixel Rendering: ft2-lcd_rendering.md
- Error Codes:
  - Error Enumerations: ft2-error_enumerations.md
  - Error Code Values: ft2-error_code_values.md
- Miscellaneous:
  - OpenType Validation: ft2-ot_validation.md
  - Incremental Loading: ft2-incremental.md
  - The TrueType Engine: ft2-truetype_engine.md
  - Glyph Color Management: ft2-color_management.md
  - TrueTypeGX/AAT Validation: ft2-gx_validation.md

# Customization
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/jquery-3.3.1.min.js
- javascripts/extra.js

# Extensions
markdown_extensions:
- toc:
    permalink: true
- pymdownx.superfences:
    disable_indented_code_blocks: true
    preserve_tabs: true

# Other Options
copyright: Copyright 2018 <a href = "http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/docs/LICENSE.TXT">The
  FreeType Project</a>.

